name: QA

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Cached by github (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#python)
          cache: 'pip'
          cache-dependency-path: |
            ./requirements.txt
            ./requirements-dev.txt

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: ./venv
          key: python-3-12-venv-${{ hashFiles('./requirements.txt') }}-${{ hashFiles('./requirements-dev.txt') }}

      - name: Install dependencies
        if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

  ruff:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            ./requirements.txt
            ./requirements-dev.txt

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: ./venv
          key: python-3-12-venv-${{ hashFiles('./requirements.txt') }}-${{ hashFiles('./requirements-dev.txt') }}

      - name: Run ruff
        run: |
          . venv/bin/activate
          ruff check --select I .
          ruff check .
          ruff format --check .

  mypy:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            ./requirements.txt
            ./requirements-dev.txt

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: ./venv
          key: python-3-12-venv-${{ hashFiles('./requirements.txt') }}-${{ hashFiles('./requirements-dev.txt') }}

      - name: Run mypy
        run: |
          . venv/bin/activate
          mypy .
